var fecha = new Date()
console.log("El año es: "+fecha.getFullYear())
console.log("El mes es: "+fecha.getMoth()+1))
console.log("El dia es: "+fecha.getDay())
console.log("La hora es: "+fecha.getHours())
console.log("El minuto es: "+fecha.getMinutes())
console.log("El Segundo es: "+fecha.getSeconds())